### ISSUE TITLE
sites.google.comのデータ引っ越しについて

### ISSUE THREAD

**Issue by nandaka-furari** [open-novel/open-novel.github.io#1]
旧公式マニュアルのデータをこっちに引っ越すのはどうでしょう。
今データをテキストにしてoldtxtフォルダに格納する作業しています。
マスターブランチにいきなり入れるのはあれなので別のブランチでコミットして
あとでプルリクエストしようと思っています。

**Comment by Hikaru02** [comment]
マニュアル類は今Wikiの方へまとめていっているのですが、どうでしょうか？
https://github.com/open-novel/open-novel.github.io/wiki
各ページ右上のEditから編集もできると思いますので、不足しているものなどあれば宜しくお願いします。

**Comment by nandaka-furari** [comment]
ちょっと言い方間違いました。マニュアルだけじゃなく、https://sites.google.com/site/openeroge/にあるデータ全てををまとめてテキストデータとして吸い出して、ここで一括管理したらどうかということです。
旧サイトは見てるといろいろ情報は古いんですが、歴史として残しておいた方いいと思いますし、そのうえでここで一括管理してみてはどうかと思いました。
mdにはしないでリポジトリの中にデータとして保存するだけです。

**Comment by nandaka-furari** [comment]
そうですね。あまり気負わずに楽にしていきます。
というわけでここはクローズします。
