### ISSUE TITLE
旧まとめサイトからの移行について

### ISSUE THREAD

**Issue by nandaka-furari** [open-novel/open-novel.github.io#2]
Wikiで吸収しきれないデータについては
GitHubPagesで管理するほかないと思い
sourceブランチを切ってそこにデータを集めています。
https://github.com/open-novel/open-novel.github.io/tree/source
このような感じで行きたいのですが
ご意見があれば幸いです。

**Comment by nandaka-furari** [comment]
クローズしたイシューと重複していると思いますが、
https://github.com/open-novel/open-novel.github.io/issues/1
趣旨としては、あくまでWikiに載せきれないデータのみの移行ということです。
Wikiを主体としていくのは変わりはありません。

**Comment by nandaka-furari** [comment]
画像などは普通のゲームのホームページのように見せるのはどうでしょうか。
途中ですが、コードはこんな感じです。
https://github.com/open-novel/open-novel.github.io/commit/80cc9372c50de11597800c3110bfe68f86faa1f0
それとGoogleアナリティクスはこちらで準備したコードを入れてあります。
共有も可能ですのでメールアドレスを送ってくれたら招待します。

**Comment by open-novel** [comment]
確かにWikiよりは、そちらのほうがずっと良さそうですね。
アナリティクスの件、忘れていました。メインページにも設定してみます。
私のメールアドレスはoao.hikaru.oao@gmail.comです。

**Comment by nandaka-furari** [comment]
データの移行はある程度済ませましたが、
スレにも書いたように旧まとめを完全代替するのはあまり意味がないことに気づきました。
なのでホームページとWikiと旧まとめを併存する方向で行くようにします。

**Comment by open-novel** [comment]
分かりました。
因みにホームページについて１つ問題があります。
https://open-novel.github.ioを一度でも開くと、open-novel.github.io下で発生する全てのネットワークアクセスを処理するサービスがブラウザにインストールされるのですが、今のままだとホームページも影響下に入ることになります。

サービスの効果は２つで、①オフライン時でも閲覧できるようにするということと、②常に最新のデータを表示するということです。
ただ、②の方のデメリットとして、すべてのデータ、今さっき表示したばかりの画像でさえも、キャッシュを使わずにもう一度問い合わせているので表示に時間がかかり、無駄があるということです。

なので画像に関しては「オフライン時でもオンライン時でもまずキャッシュから読み込むことにする」ように変更しようかと思います。
もしすでに存在している画像を更新した場合はその後の１回目の表示では古い画像が表示されることになりますが、そのようなことはあまりなく、あっても問題は小さいと思うのですが、どうでしょうか。

**Comment by nandaka-furari** [comment]
source以下のファイルでは大きいものは画像のみなので、その対策で大丈夫だと思います。
ただ、今後もしかしたら音声や動画が入るかもしれませんので、その時はまた考える必要があるでしょう。
あまり可能性はないでしょうけど…。

**Comment by open-novel** [comment]
取り敢えずメディア類と追加で読み込むファイルは積極的にキャッシュするように調整しました。
なにか気になることがあればいつでも言ってください。
もしくはナンダカフラリさんはJavaScriptの勉強もされてるそうですから、source下にServiceWorkerのファイルを置けばそこから先をお好みの挙動で管理することもできます。
