### ISSUE TITLE
アナリティクスについて

### ISSUE THREAD

**Issue by open-novel** [open-novel/open-novel.github.io#4]
前回の更新で対策したのでおそらくもうローカルからのアクセスはカウントされてないと思います
自分たちのアクセスを防ぐにはブラウザのコンソールで
localStorage.DoNotAnalytic = 'Yes'
と一度すれば以後防げると思います

**Comment by nandaka-furari** [comment]
なるほど、いろいろやり方があるんですね。勉強になります。

**Comment by nandaka-furari** [comment]
ついでに気になっているのですが、ホームページのアナリティクスのトラッキングIDはプレイヤーページのものに統一してもいいかなと思ってるんですが。どうでしょう。別々の方がいいでしょうか。

**Comment by open-novel** [comment]
私もどちらかと言うと、統一したほうが良い気がします。

**Comment by nandaka-furari** [comment]
それならホームページの方のIDはプレイヤーのものに置き換えておきます。

**Comment by nandaka-furari** [comment]
IDは書き換えました。
アナリティクスを確認したところ、ちゃんと動いているようです。

**Comment by nandaka-furari** [comment]
コンソールで
localStorage.DoNotAnalytic
とするとundefinedになるのですがこれは設定されていないということでしょうか。

**Comment by open-novel** [comment]
そうですね。プレイヤーの設定リセット等を行うとこれも解除されてしまうので
よりわかりやすいようプレイヤーにデバッグモードの機能を載せます

**Comment by nandaka-furari** [comment]
自分のアクセスのカウントが邪魔くさいので
フィルタに私のIPアドレスを追加してもらえませんか？
スマフォからのアクセスが集計されているようです。
アドレスはメールで送ります。

**Comment by open-novel** [comment]
スマホのIPアドレスは頻繁に変わるので効果は薄いと思います。
自宅の固定回線であっても停電などでルーターが再起動した際などには
変わる契約になってることがほとんどだと思います。

とりあえずプレイヤーの設定から無効にできるようにするのと
起動画面に無効化できてるか表示しようと思うのですが
それでどうでしょうか？

**Comment by nandaka-furari** [comment]
それの方が確実でしょうから、それでお願いします。
