### ISSUE TITLE
プロジェクトの名前について

### ISSUE THREAD

**Issue by nandaka-furari** [open-novel/open-novel.github.io#6]
本スレにも書きましたがプロジェクト名の「エロゲ」という部分は見直した方がいい気持ちになっています。
より多くの人を集められるプロジェクト名に変えることを検討すべきではないでしょうか。

**Comment by nandaka-furari** [comment]
色々考えなおしたのですが、名前に関しては今すぐ何かの結論をださず、数年後を見据えてゆっくり行くくらいがいいかもしれません。
人手が足りないといっても人が来すぎても進行が難しいかもしれません。
今は、とりあえず今のペースがちょうどいい、という感じです。

ただ、課題であることは間違いないと思っていますのでイシューはそのままにしておきたいです。

**Comment by open-novel** [comment]
個人的には「エロゲ」は外した方が良いとずっと思っています。
勿論「エロゲ」も歓迎しますが、それを大きく掲げると間口が狭くなるのではないかと思うからです。
ナンダカフラリさんが良ければ名前を変えてみませんか。

**Comment by nandaka-furari** [comment]
とりあえず新スレを作ってみるのがいいと思います。テンプレはこんなでどうでしょう。
https://github.com/open-novel/open-novel.github.io/wiki/%E3%81%8A%E3%83%BC%E3%81%B7%E3%82%93%E3%81%A7%E3%83%8E%E3%83%99%E3%83%AB%E3%82%B2%E3%83%BC%E4%BD%9C%E3%82%8D%E3%81%86%E3%81%9C%E3%81%A8%E3%81%AF
エロゲ製作プロジェクトはそのまま存続させるのがいいと思います。製作のノウハウを語る場は必要でしょうから。

**Comment by nandaka-furari** [comment]
私の一存でひとまずこのリポジトリの名称は「おーぷんでノベルゲー作ろうぜ」に改称。
「オープンでエロゲ作ろうぜ」は存続させつつもサブプロジェクト扱いということに。
ホームページも変えたいですが時間はかかります。

ということでここは閉じます。
